name = "ricorra-pwa"
compatibility_date = "2025-09-27"
main = "_worker.js"

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "DB"
id = "f60c18ff44194c2a9c91095e15732502"

[triggers]
crons = ["0 9 * * *", "*/30 * * * *"]
